version: 2.1

orbs:
  android: circleci/android@0.2.0

jobs:
  build:
    executor: android/android
    steps:
      - checkout
      - run:
          name: Check, test and build the app.
          command: |
            echo "NEXUS_USERNAME=$NEXUS_USERNAME" >> gradle.properties
            echo "NEXUS_PASSWORD=$NEXUS_PASSWORD" >> gradle.properties
            ./gradlew check bundleReleaseAar
      - store_artifacts:
          path: library/build/outputs/aar

  publish-to-ossrh:
    executor: android/android
    steps:
      - checkout
      - run:
          name: Publish the lib to OSSRH.
          command: |
            echo "NEXUS_USERNAME=$NEXUS_USERNAME" >> gradle.properties
            echo "NEXUS_PASSWORD=$NEXUS_PASSWORD" >> gradle.properties
            echo "signing.keyId=$PGP_SIGNING_KEY_ID" >> gradle.properties
            echo "signing.password=$PGP_SIGNING_PASSWORD" >> gradle.properties
            echo "signing.secretKeyRingFile=../secring.gpg" >> gradle.properties
            # convert to env var
            # - base64 ~/.gnupg/secring.gpg > ./secring.gpg.base64
            # - Copy content of ./secring.gpg.base64 to env var
            echo $PGP_SECRING_BASE64 | base64 --decode > secring.gpg
            ./gradlew publish
      - persist_to_workspace:
          root: library/build/outputs/
          paths:
            - aar/*.aar

  publish-github-release:
    docker:
      - image: circleci/golang:1.10
    steps:
      - attach_workspace:
          at: ./artifacts
      - run:
          name: "Publish Release on GitHub"
          command: |
            go get github.com/tcnksm/ghr
            ghr -t ${GITHUB_PERSONAL_ACCESS_TOKEN} -u ${CIRCLE_PROJECT_USERNAME} -r ${CIRCLE_PROJECT_REPONAME} -c ${CIRCLE_SHA1} ${CIRCLE_TAG} ./artifacts/aar/*-release.aar

workflows:
  version: 2
  build-n-publish:
    jobs:
      - build
      - publish-to-ossrh:
          filters:
            tags:
              only: /^v.*/
            branches:
              ignore: /.*/
      - publish-github-release:
          requires:
            - publish-to-ossrh
          filters:
            tags:
              only: /^v.*/
            branches:
              ignore: /.*/
